### ISSUE TITLE
Problemas con activo como llave foránea

### ISSUE THREAD

**Issue by daniel134** [jvander5/Decanatura#42]
Estuve modificando los "delete" de tipo y marca para que mostrara un mensaje flash en lugar de la pantalla de error de cakephp cuando se intenta eliminar una llave foránea. El problema de la tabla activos es que no se puede "eliminar" un activo que haya sido parte de un préstamo, y el historial de préstamos tampoco se puede eliminar, por lo que en estos momentos hay activos que no pueden ser eliminados hasta que sean eliminados los préstamos en los que estuvo.

**Comment by roymm** [comment]
Creo que esto se arregla cuando @jvander5 haga la funcionalidad de agregar n activos a un préstamo, porque la llave foranea de préstamos a activos se elimina y se agrega una de activos a préstamos.

**Comment by roymm** [comment]
Solucionado al completar el issue #43
