### ISSUE TITLE
Poner en español "Seleccionar Archivo" al agregar imagen y archivo.

### ISSUE THREAD

**Issue by daniel134** [jvander5/Decanatura#57]

**Comment by daniel134** [comment]
No pude encontrar cómo resolverlo, hice una búsqueda casi exhaustiva por los archivos de cake que tenían que ver con subir un archivo. Siento que sí es algo del idioma del navegador que uno utilice. Incluso la documentación de bootstrap que viene toda en inglés presenta el ejemplo con el botón en Español: https://getbootstrap.com/docs/4.0/components/forms/

**Comment by roymm** [comment]
Sí, creo que es el idioma del browser lo que determina ese mensaje
