### ISSUE TITLE
Vista de editar activo

### ISSUE THREAD

**Issue by roymm** [jvander5/Decanatura#64]
Se debe de cambiar la vista de préstamos para que los labels y los inputs estén en la misma fila. Además, los inputs pequeños se deben de agregar en la misma fila con dos columnas y los inputs grandes solos en una fila.

Se debe hacer igual que en el issue #49

**Comment by daniel134** [comment]
No sé si era la vista de editar activo o la de préstamos pero ya arreglé la de insertar préstamo que era la que estaba mal.
