### ISSUE TITLE
Problemas con espacio "Año" en Assets 

### ISSUE THREAD

**Issue by roymm** [jvander5/Decanatura#8]
El espacio de año se puede escoger correctamente en la vista add.ctp y en edit.ctp pero el controller AssetsController.php no lo recibe corectamente, recibe la fecha actual. Además, no se despliega correctamente en el index.ctp ni el el view.ctp

**Comment by daniel134** [comment]
No se puede dejar como un entero normal? En lugar de date que pide la fecha exacta

**Comment by roymm** [comment]
Sí se puede, pero se ve mal a la hora de desplegarlo. Se ve como "2,018"
